version: '3'
services:
  web:
    image: php:apache
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    ports:
      - "8080:80"

  mysql:
    build:
      context: ./db
    ports:
      - "3306:3306"
